name: Test Symfony
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Set up environment variables
        env:
          APP_ENV: 'test'
          KERNEL_CLASS: 'App\Kernel'
          APP_SECRET: '${{ secrets.APP_SECRET }}'
          SYMFONY_DEPRECATIONS_HELPER: '999999'
          PANTHER_APP_ENV: 'panther'
          PANTHER_ERROR_SCREENSHOT_DIR: './var/error-screenshots'
          DATABASE_URL: '${{ secrets.DATABASE_URL }}'
          MYSQL_DATABASE: '${{ secrets.MYSQL_DATABASE }}'
          MYSQL_PASSWORD: '${{ secrets.MYSQL_PASSWORD }}'
          MYSQL_ROOT_PASSWORD: '${{ secrets.MYSQL_ROOT_PASSWORD }}'
          MYSQL_USER: '${{ secrets.MYSQL_USER }}'
        run: |
          echo "APP_ENV=${APP_ENV}" >> $GITHUB_ENV
          echo "KERNEL_CLASS=${KERNEL_CLASS}" >> $GITHUB_ENV
          echo "SYMFONY_DEPRECATIONS_HELPER=${SYMFONY_DEPRECATIONS_HELPER}" >> $GITHUB_ENV
          echo "PANTHER_APP_ENV=${PANTHER_APP_ENV}" >> $GITHUB_ENV
          echo "PANTHER_ERROR_SCREENSHOT_DIR=${PANTHER_ERROR_SCREENSHOT_DIR}" >> $GITHUB_ENV
          echo "DATABASE_URL=${DATABASE_URL}" >> $GITHUB_ENV
          echo "MYSQL_DATABASE=${MYSQL_DATABASE}" >> $GITHUB_ENV
          echo "MYSQL_PASSWORD=${MYSQL_PASSWORD}" >> $GITHUB_ENV
          echo "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}" >> $GITHUB_ENV
          echo "MYSQL_USER=${MYSQL_USER}" >> $GITHUB_ENV

      - name: Prepare database
        run: php bin/console doctrine:database:create --env=test

      - name: Run PHPUnit tests
        run: php bin/phpunit
