name: Test Symfony
on: 
  push:
    branches:
      - 'features/cng-*'
  pull_request:
    branches:
      - dev

jobs:
  branch-validation:
    runs-on: ubuntu-latest

    steps:
    - name: Check branch name format
      id: check_branch_name
      run: |
        branch_name=$(echo "${GITHUB_REF#refs/heads/}")
        if [[ ! "$branch_name" =~ ^features/cng-[0-9]+$ ]]; then
          echo "Error: Invalid branch name format. Branch names must follow the format 'features/cng-XX' without capital letters."
          exit 1
        fi

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install MySQL
        run: sudo apt-get install mysql-server -y

      - name: Start MySQL service
        run: sudo service mysql start

      - name: Check MySQL service status
        run: sudo service mysql status

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Set up environment variables
        env:
          APP_ENV: 'test'
          KERNEL_CLASS: 'App\Kernel'
          APP_SECRET: '${{ secrets.APP_SECRET }}'
          SYMFONY_DEPRECATIONS_HELPER: '999999'
          PANTHER_APP_ENV: 'panther'
          PANTHER_ERROR_SCREENSHOT_DIR: './var/error-screenshots'
          DATABASE_URL: 'mysql://root:root@127.0.0.1:3306/${{ secrets.MYSQL_DATABASE }}?serverVersion=8.0.32&charset=utf8mb4'
        run: |
          echo "APP_ENV=${APP_ENV}" >> $GITHUB_ENV
          echo "KERNEL_CLASS=${KERNEL_CLASS}" >> $GITHUB_ENV
          echo "SYMFONY_DEPRECATIONS_HELPER=${SYMFONY_DEPRECATIONS_HELPER}" >> $GITHUB_ENV
          echo "PANTHER_APP_ENV=${PANTHER_APP_ENV}" >> $GITHUB_ENV
          echo "PANTHER_ERROR_SCREENSHOT_DIR=${PANTHER_ERROR_SCREENSHOT_DIR}" >> $GITHUB_ENV
          echo "DATABASE_URL=${DATABASE_URL}" >> $GITHUB_ENV

      - name: Debug database connection
        run: echo "DATABASE_URL=mysql://root:root@127.0.0.1:3306/${{ secrets.MYSQL_DATABASE }}?serverVersion=8.0.32&charset=utf8mb4"

      - name: Prepare database
        run: php bin/console doctrine:database:create --env=test

      - name: Run PHPUnit tests
        run: php bin/phpunit